apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: smart-crawler
    kind: bps-daerah
  name: bps-daerah-worker
  namespace: nextgen
spec:
  replicas: 50
  selector:
    matchLabels:
      app: smart-crawler
      kind: bps-daerah
  template:
    metadata:
      labels:
        app: smart-crawler
        kind: bps-daerah
    spec:
      containers:
        - name: bps-daerah-worker
          image: 192.168.202.50/clipper/smart-crawler/bps_daerah_worker
          imagePullPolicy: Always
          nodeSelector:
              crawler: bps
          volumeMounts:
            - mountPath: /app/config.ini
              name: config
              subPath: config.ini
      volumes:
        - configMap:
            name: config-bps-daerah
          name: config
